[profile.default]
optimizer = true
optimizer_runs = 20000
fuzz_runs = 100
verbosity= 2
gas_reports = ["*"]
libs = ['lib']
cache_path  = 'forge-cache'

[profile.ci]
fuzz_runs = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
